# Generated by Django 5.2 on 2025-04-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitlane', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner',
            new_name='customer',
        ),
    ]
